
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service
          uri: lb://service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
      discovery:
         locator:
           enabled: true
           lowerCaseServiceId: true 
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: true



service:
  instances:
    - uri: java-app-1:8080
    - uri: java-app-2:8080
    - uri: java-app-3:8080





